// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itg.soabus.contract.domain;

import com.itg.soabus.contract.domain.TradeContractItem;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TradeContractItem_Roo_Configurable {
    
    declare @type: TradeContractItem: @Configurable;
    
}
