// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itg.soabus.logistic.domain;

import com.itg.soabus.logistic.domain.StorageLocation;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect StorageLocation_Roo_Configurable {
    
    declare @type: StorageLocation: @Configurable;
    
}
