package com.itg.soabus.oaservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-26T12:48:16.241+08:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://localhost/services/RequestService", name = "RequestServicePortType")
@XmlSeeAlso({ObjectFactory.class, weaver.workflow.request.ObjectFactory.class, weaver.hrm.ObjectFactory.class, weaver.soa.workflow.request.ObjectFactory.class, weaver.conn.ObjectFactory.class})
public interface RequestServicePortType {

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "nextNodeByReject", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.NextNodeByReject")
    @WebMethod
    @ResponseWrapper(localName = "nextNodeByRejectResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.NextNodeByRejectResponse")
    public boolean nextNodeByReject(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in2
    );

    @RequestWrapper(localName = "writeLog", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.WriteLog")
    @WebMethod
    @ResponseWrapper(localName = "writeLogResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.WriteLogResponse")
    public void writeLog(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        java.lang.Object in0
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getRequest", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetRequest")
    @WebMethod
    @ResponseWrapper(localName = "getRequestResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetRequestResponse")
    public weaver.soa.workflow.request.RequestInfo getRequest(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        int in0
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getHendledRequestBySearch", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetHendledRequestBySearch")
    @WebMethod
    @ResponseWrapper(localName = "getHendledRequestBySearchResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetHendledRequestBySearchResponse")
    public weaver.soa.workflow.request.ArrayOfRequestBase getHendledRequestBySearch(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in3
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getRequest3", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetRequest3")
    @WebMethod
    @ResponseWrapper(localName = "getRequest3Response", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetRequest3Response")
    public weaver.soa.workflow.request.RequestInfo getRequest3(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        weaver.workflow.request.RequestManager in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        int in1
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "createRequest", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.CreateRequest")
    @WebMethod
    @ResponseWrapper(localName = "createRequestResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.CreateRequestResponse")
    public java.lang.String createRequest(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        weaver.soa.workflow.request.RequestInfo in0
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getRequestLogs", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetRequestLogs")
    @WebMethod
    @ResponseWrapper(localName = "getRequestLogsResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetRequestLogsResponse")
    public weaver.soa.workflow.request.ArrayOfLog getRequestLogs(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
        int in2
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getRequest1", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetRequest1")
    @WebMethod
    @ResponseWrapper(localName = "getRequest1Response", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetRequest1Response")
    public weaver.soa.workflow.request.RequestInfo getRequest1(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        weaver.workflow.request.RequestManager in0
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getProcessedRequestBySearch", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetProcessedRequestBySearch")
    @WebMethod
    @ResponseWrapper(localName = "getProcessedRequestBySearchResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetProcessedRequestBySearchResponse")
    public weaver.soa.workflow.request.ArrayOfRequestBase getProcessedRequestBySearch(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in3
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "nextNodeBySubmit", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.NextNodeBySubmit")
    @WebMethod
    @ResponseWrapper(localName = "nextNodeBySubmitResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.NextNodeBySubmitResponse")
    public boolean nextNodeBySubmit(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        weaver.soa.workflow.request.RequestInfo in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in3
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getMyRequestBySearch", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetMyRequestBySearch")
    @WebMethod
    @ResponseWrapper(localName = "getMyRequestBySearchResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetMyRequestBySearchResponse")
    public weaver.soa.workflow.request.ArrayOfRequestBase getMyRequestBySearch(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in3
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getRequest2", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetRequest2")
    @WebMethod
    @ResponseWrapper(localName = "getRequest2Response", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetRequest2Response")
    public weaver.soa.workflow.request.RequestInfo getRequest2(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        int in1
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getPropValue", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetPropValue")
    @WebMethod
    @ResponseWrapper(localName = "getPropValueResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetPropValueResponse")
    public java.lang.String getPropValue(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in1
    );

    @RequestWrapper(localName = "writeLog1", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.WriteLog1")
    @WebMethod
    @ResponseWrapper(localName = "writeLog1Response", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.WriteLog1Response")
    public void writeLog1(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        java.lang.Object in1
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getRightMenu", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetRightMenu")
    @WebMethod
    @ResponseWrapper(localName = "getRightMenuResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetRightMenuResponse")
    public java.lang.String getRightMenu(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost/services/RequestService")
        int in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost/services/RequestService")
        boolean in5
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "forwardFlow", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.ForwardFlow")
    @WebMethod
    @ResponseWrapper(localName = "forwardFlowResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.ForwardFlowResponse")
    public boolean forwardFlow(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in4
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getPendingRequestBySearch", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetPendingRequestBySearch")
    @WebMethod
    @ResponseWrapper(localName = "getPendingRequestBySearchResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.GetPendingRequestBySearchResponse")
    public weaver.soa.workflow.request.ArrayOfRequestBase getPendingRequestBySearch(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in3
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "nextNodeBySubmit1", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.NextNodeBySubmit1")
    @WebMethod
    @ResponseWrapper(localName = "nextNodeBySubmit1Response", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.NextNodeBySubmit1Response")
    public boolean nextNodeBySubmit1(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        weaver.soa.workflow.request.RequestInfo in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in4
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "whetherMustInputRemark", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.WhetherMustInputRemark")
    @WebMethod
    @ResponseWrapper(localName = "whetherMustInputRemarkResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.WhetherMustInputRemarkResponse")
    public boolean whetherMustInputRemark(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost/services/RequestService")
        int in4
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "deleteRequest", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.DeleteRequest")
    @WebMethod
    @ResponseWrapper(localName = "deleteRequestResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.DeleteRequestResponse")
    public boolean deleteRequest(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        int in0
    );

    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "LoadTemplateProp", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.LoadTemplateProp")
    @WebMethod(operationName = "LoadTemplateProp")
    @ResponseWrapper(localName = "LoadTemplatePropResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.itg.soabus.oaservice.LoadTemplatePropResponse")
    public com.itg.soabus.oaservice.AnyType2AnyTypeMap loadTemplateProp(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
        java.lang.String in0
    );
}
