
package com.itg.soabus.oaservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-26T12:48:15.275+08:00
 * Generated source version: 2.7.5
 * 
 */
public final class RequestServicePortType_RequestServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://localhost/services/RequestService", "RequestService");

    private RequestServicePortType_RequestServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RequestService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RequestService ss = new RequestService(wsdlURL, SERVICE_NAME);
        RequestServicePortType port = ss.getRequestServiceHttpPort();  
        
        {
        System.out.println("Invoking nextNodeByReject...");
        int _nextNodeByReject_in0 = -879153006;
        int _nextNodeByReject_in1 = 574721371;
        java.lang.String _nextNodeByReject_in2 = "_nextNodeByReject_in2-1649094652";
        boolean _nextNodeByReject__return = port.nextNodeByReject(_nextNodeByReject_in0, _nextNodeByReject_in1, _nextNodeByReject_in2);
        System.out.println("nextNodeByReject.result=" + _nextNodeByReject__return);


        }
        {
        System.out.println("Invoking writeLog...");
        java.lang.Object _writeLog_in0 = null;
        port.writeLog(_writeLog_in0);


        }
        {
        System.out.println("Invoking getRequest...");
        int _getRequest_in0 = 1346170525;
        weaver.soa.workflow.request.RequestInfo _getRequest__return = port.getRequest(_getRequest_in0);
        System.out.println("getRequest.result=" + _getRequest__return);


        }
        {
        System.out.println("Invoking getHendledRequestBySearch...");
        int _getHendledRequestBySearch_in0 = 1127520473;
        java.lang.String _getHendledRequestBySearch_in1 = "_getHendledRequestBySearch_in11963421723";
        java.lang.String _getHendledRequestBySearch_in2 = "_getHendledRequestBySearch_in2-776960654";
        java.lang.String _getHendledRequestBySearch_in3 = "_getHendledRequestBySearch_in3-1101878786";
        weaver.soa.workflow.request.ArrayOfRequestBase _getHendledRequestBySearch__return = port.getHendledRequestBySearch(_getHendledRequestBySearch_in0, _getHendledRequestBySearch_in1, _getHendledRequestBySearch_in2, _getHendledRequestBySearch_in3);
        System.out.println("getHendledRequestBySearch.result=" + _getHendledRequestBySearch__return);


        }
        {
        System.out.println("Invoking getRequest3...");
        weaver.workflow.request.RequestManager _getRequest3_in0 = new weaver.workflow.request.RequestManager();
        _getRequest3_in0.setBeAgenter(Integer.valueOf(-954611306));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0BillTableName = null;
        _getRequest3_in0.setBillTableName(_getRequest3_in0BillTableName);
        _getRequest3_in0.setBillid(Integer.valueOf(1848224474));
        _getRequest3_in0.setCanModify(Boolean.valueOf(true));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0ClientType = null;
        _getRequest3_in0.setClientType(_getRequest3_in0ClientType);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Coadsigntype = null;
        _getRequest3_in0.setCoadsigntype(_getRequest3_in0Coadsigntype);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Createdate = null;
        _getRequest3_in0.setCreatedate(_getRequest3_in0Createdate);
        _getRequest3_in0.setCreater(Integer.valueOf(1813155802));
        _getRequest3_in0.setCreatertype(Integer.valueOf(258653317));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Createtime = null;
        _getRequest3_in0.setCreatetime(_getRequest3_in0Createtime);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0CurrentDate = null;
        _getRequest3_in0.setCurrentDate(_getRequest3_in0CurrentDate);
        javax.xml.bind.JAXBElement<com.itg.soabus.oaservice.AnyType2AnyType2AnyTypeMapMap> _getRequest3_in0CurrentOperator = null;
        _getRequest3_in0.setCurrentOperator(_getRequest3_in0CurrentOperator);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0CurrentTime = null;
        _getRequest3_in0.setCurrentTime(_getRequest3_in0CurrentTime);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Docrowindex = null;
        _getRequest3_in0.setDocrowindex(_getRequest3_in0Docrowindex);
        _getRequest3_in0.setFormid(Integer.valueOf(2074342961));
        _getRequest3_in0.setHandWrittenSign(Integer.valueOf(1348086333));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0HasTriggeredSubwf = null;
        _getRequest3_in0.setHasTriggeredSubwf(_getRequest3_in0HasTriggeredSubwf);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Intervenorid = null;
        _getRequest3_in0.setIntervenorid(_getRequest3_in0Intervenorid);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0IsFromEditDocument = null;
        _getRequest3_in0.setIsFromEditDocument(_getRequest3_in0IsFromEditDocument);
        _getRequest3_in0.setIsPending(Integer.valueOf(1601879780));
        _getRequest3_in0.setIsagentCreater(Integer.valueOf(-611226456));
        _getRequest3_in0.setIsbill(Integer.valueOf(-884382107));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Iscreate = null;
        _getRequest3_in0.setIscreate(_getRequest3_in0Iscreate);
        _getRequest3_in0.setIsremark(Integer.valueOf(-1258955739));
        _getRequest3_in0.setLastNodeid(Integer.valueOf(109761432));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Lastnodetype = null;
        _getRequest3_in0.setLastnodetype(_getRequest3_in0Lastnodetype);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Lastoperatedate = null;
        _getRequest3_in0.setLastoperatedate(_getRequest3_in0Lastoperatedate);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Lastoperatetime = null;
        _getRequest3_in0.setLastoperatetime(_getRequest3_in0Lastoperatetime);
        _getRequest3_in0.setLastoperator(Integer.valueOf(613489055));
        _getRequest3_in0.setLastoperatortype(Integer.valueOf(-1555329484));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Message = null;
        _getRequest3_in0.setMessage(_getRequest3_in0Message);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0MessageType = null;
        _getRequest3_in0.setMessageType(_getRequest3_in0MessageType);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Messagecontent = null;
        _getRequest3_in0.setMessagecontent(_getRequest3_in0Messagecontent);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Messageid = null;
        _getRequest3_in0.setMessageid(_getRequest3_in0Messageid);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Needwfback = null;
        _getRequest3_in0.setNeedwfback(_getRequest3_in0Needwfback);
        _getRequest3_in0.setNextNodeid(Integer.valueOf(1558938994));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0NextNodetype = null;
        _getRequest3_in0.setNextNodetype(_getRequest3_in0NextNodetype);
        _getRequest3_in0.setNodeid(Integer.valueOf(-1483943261));
        _getRequest3_in0.setNodelefttime(Float.valueOf(0.2298572f));
        _getRequest3_in0.setNodepasstime(Float.valueOf(0.49527794f));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Nodetype = null;
        _getRequest3_in0.setNodetype(_getRequest3_in0Nodetype);
        _getRequest3_in0.setPassedGroups(Integer.valueOf(-1112960029));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Remark = null;
        _getRequest3_in0.setRemark(_getRequest3_in0Remark);
        _getRequest3_in0.setRequestKey(Integer.valueOf(-1441278590));
        _getRequest3_in0.setRequestid(Integer.valueOf(-1565667242));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Requestlevel = null;
        _getRequest3_in0.setRequestlevel(_getRequest3_in0Requestlevel);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Requestname = null;
        _getRequest3_in0.setRequestname(_getRequest3_in0Requestname);
        javax.xml.bind.JAXBElement<weaver.conn.RecordSetTrans> _getRequest3_in0RsTrans = null;
        _getRequest3_in0.setRsTrans(_getRequest3_in0RsTrans);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Signdocids = null;
        _getRequest3_in0.setSigndocids(_getRequest3_in0Signdocids);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Signworkflowids = null;
        _getRequest3_in0.setSignworkflowids(_getRequest3_in0Signworkflowids);
        _getRequest3_in0.setSpeechAttachment(Integer.valueOf(673986091));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Src = null;
        _getRequest3_in0.setSrc(_getRequest3_in0Src);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Status = null;
        _getRequest3_in0.setStatus(_getRequest3_in0Status);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0SubmitNodeId = null;
        _getRequest3_in0.setSubmitNodeId(_getRequest3_in0SubmitNodeId);
        _getRequest3_in0.setTotalGroups(Integer.valueOf(-444225829));
        javax.xml.bind.JAXBElement<weaver.hrm.User> _getRequest3_in0User = null;
        _getRequest3_in0.setUser(_getRequest3_in0User);
        _getRequest3_in0.setUserId(Integer.valueOf(1451122024));
        _getRequest3_in0.setUserType(Integer.valueOf(-690579491));
        _getRequest3_in0.setWorkflowid(Integer.valueOf(-233236363));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest3_in0Workflowtype = null;
        _getRequest3_in0.setWorkflowtype(_getRequest3_in0Workflowtype);
        int _getRequest3_in1 = -585385316;
        weaver.soa.workflow.request.RequestInfo _getRequest3__return = port.getRequest3(_getRequest3_in0, _getRequest3_in1);
        System.out.println("getRequest3.result=" + _getRequest3__return);


        }
        {
        System.out.println("Invoking createRequest...");
        weaver.soa.workflow.request.RequestInfo _createRequest_in0 = new weaver.soa.workflow.request.RequestInfo();
        javax.xml.bind.JAXBElement<java.lang.String> _createRequest_in0Creatorid = null;
        _createRequest_in0.setCreatorid(_createRequest_in0Creatorid);
        javax.xml.bind.JAXBElement<java.lang.String> _createRequest_in0Description = null;
        _createRequest_in0.setDescription(_createRequest_in0Description);
        javax.xml.bind.JAXBElement<weaver.soa.workflow.request.DetailTableInfo> _createRequest_in0DetailTableInfo = null;
        _createRequest_in0.setDetailTableInfo(_createRequest_in0DetailTableInfo);
        javax.xml.bind.JAXBElement<java.lang.String> _createRequest_in0Hostid = null;
        _createRequest_in0.setHostid(_createRequest_in0Hostid);
        javax.xml.bind.JAXBElement<java.lang.String> _createRequest_in0IsNextFlow = null;
        _createRequest_in0.setIsNextFlow(_createRequest_in0IsNextFlow);
        javax.xml.bind.JAXBElement<java.lang.String> _createRequest_in0Lastoperator = null;
        _createRequest_in0.setLastoperator(_createRequest_in0Lastoperator);
        javax.xml.bind.JAXBElement<weaver.soa.workflow.request.MainTableInfo> _createRequest_in0MainTableInfo = null;
        _createRequest_in0.setMainTableInfo(_createRequest_in0MainTableInfo);
        javax.xml.bind.JAXBElement<java.lang.String> _createRequest_in0Remindtype = null;
        _createRequest_in0.setRemindtype(_createRequest_in0Remindtype);
        javax.xml.bind.JAXBElement<weaver.soa.workflow.request.RequestLog> _createRequest_in0RequestLog = null;
        _createRequest_in0.setRequestLog(_createRequest_in0RequestLog);
        javax.xml.bind.JAXBElement<weaver.workflow.request.RequestManager> _createRequest_in0RequestManager = null;
        _createRequest_in0.setRequestManager(_createRequest_in0RequestManager);
        javax.xml.bind.JAXBElement<java.lang.String> _createRequest_in0Requestid = null;
        _createRequest_in0.setRequestid(_createRequest_in0Requestid);
        javax.xml.bind.JAXBElement<java.lang.String> _createRequest_in0Requestlevel = null;
        _createRequest_in0.setRequestlevel(_createRequest_in0Requestlevel);
        javax.xml.bind.JAXBElement<weaver.conn.RecordSetTrans> _createRequest_in0RsTrans = null;
        _createRequest_in0.setRsTrans(_createRequest_in0RsTrans);
        javax.xml.bind.JAXBElement<java.lang.String> _createRequest_in0Workflowid = null;
        _createRequest_in0.setWorkflowid(_createRequest_in0Workflowid);
        java.lang.String _createRequest__return = port.createRequest(_createRequest_in0);
        System.out.println("createRequest.result=" + _createRequest__return);


        }
        {
        System.out.println("Invoking getRequestLogs...");
        java.lang.String _getRequestLogs_in0 = "_getRequestLogs_in0-1206620060";
        int _getRequestLogs_in1 = -1278559441;
        int _getRequestLogs_in2 = -2132690462;
        weaver.soa.workflow.request.ArrayOfLog _getRequestLogs__return = port.getRequestLogs(_getRequestLogs_in0, _getRequestLogs_in1, _getRequestLogs_in2);
        System.out.println("getRequestLogs.result=" + _getRequestLogs__return);


        }
        {
        System.out.println("Invoking getRequest1...");
        weaver.workflow.request.RequestManager _getRequest1_in0 = new weaver.workflow.request.RequestManager();
        _getRequest1_in0.setBeAgenter(Integer.valueOf(144200372));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0BillTableName = null;
        _getRequest1_in0.setBillTableName(_getRequest1_in0BillTableName);
        _getRequest1_in0.setBillid(Integer.valueOf(1725424835));
        _getRequest1_in0.setCanModify(Boolean.valueOf(true));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0ClientType = null;
        _getRequest1_in0.setClientType(_getRequest1_in0ClientType);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Coadsigntype = null;
        _getRequest1_in0.setCoadsigntype(_getRequest1_in0Coadsigntype);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Createdate = null;
        _getRequest1_in0.setCreatedate(_getRequest1_in0Createdate);
        _getRequest1_in0.setCreater(Integer.valueOf(-1460175952));
        _getRequest1_in0.setCreatertype(Integer.valueOf(1532385206));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Createtime = null;
        _getRequest1_in0.setCreatetime(_getRequest1_in0Createtime);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0CurrentDate = null;
        _getRequest1_in0.setCurrentDate(_getRequest1_in0CurrentDate);
        javax.xml.bind.JAXBElement<com.itg.soabus.oaservice.AnyType2AnyType2AnyTypeMapMap> _getRequest1_in0CurrentOperator = null;
        _getRequest1_in0.setCurrentOperator(_getRequest1_in0CurrentOperator);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0CurrentTime = null;
        _getRequest1_in0.setCurrentTime(_getRequest1_in0CurrentTime);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Docrowindex = null;
        _getRequest1_in0.setDocrowindex(_getRequest1_in0Docrowindex);
        _getRequest1_in0.setFormid(Integer.valueOf(-792232270));
        _getRequest1_in0.setHandWrittenSign(Integer.valueOf(927655295));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0HasTriggeredSubwf = null;
        _getRequest1_in0.setHasTriggeredSubwf(_getRequest1_in0HasTriggeredSubwf);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Intervenorid = null;
        _getRequest1_in0.setIntervenorid(_getRequest1_in0Intervenorid);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0IsFromEditDocument = null;
        _getRequest1_in0.setIsFromEditDocument(_getRequest1_in0IsFromEditDocument);
        _getRequest1_in0.setIsPending(Integer.valueOf(1481647976));
        _getRequest1_in0.setIsagentCreater(Integer.valueOf(563125293));
        _getRequest1_in0.setIsbill(Integer.valueOf(-1059339224));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Iscreate = null;
        _getRequest1_in0.setIscreate(_getRequest1_in0Iscreate);
        _getRequest1_in0.setIsremark(Integer.valueOf(477022672));
        _getRequest1_in0.setLastNodeid(Integer.valueOf(1882963811));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Lastnodetype = null;
        _getRequest1_in0.setLastnodetype(_getRequest1_in0Lastnodetype);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Lastoperatedate = null;
        _getRequest1_in0.setLastoperatedate(_getRequest1_in0Lastoperatedate);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Lastoperatetime = null;
        _getRequest1_in0.setLastoperatetime(_getRequest1_in0Lastoperatetime);
        _getRequest1_in0.setLastoperator(Integer.valueOf(-1955447602));
        _getRequest1_in0.setLastoperatortype(Integer.valueOf(324971266));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Message = null;
        _getRequest1_in0.setMessage(_getRequest1_in0Message);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0MessageType = null;
        _getRequest1_in0.setMessageType(_getRequest1_in0MessageType);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Messagecontent = null;
        _getRequest1_in0.setMessagecontent(_getRequest1_in0Messagecontent);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Messageid = null;
        _getRequest1_in0.setMessageid(_getRequest1_in0Messageid);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Needwfback = null;
        _getRequest1_in0.setNeedwfback(_getRequest1_in0Needwfback);
        _getRequest1_in0.setNextNodeid(Integer.valueOf(-1928834572));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0NextNodetype = null;
        _getRequest1_in0.setNextNodetype(_getRequest1_in0NextNodetype);
        _getRequest1_in0.setNodeid(Integer.valueOf(-945269873));
        _getRequest1_in0.setNodelefttime(Float.valueOf(0.6945848f));
        _getRequest1_in0.setNodepasstime(Float.valueOf(0.88887817f));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Nodetype = null;
        _getRequest1_in0.setNodetype(_getRequest1_in0Nodetype);
        _getRequest1_in0.setPassedGroups(Integer.valueOf(1285059352));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Remark = null;
        _getRequest1_in0.setRemark(_getRequest1_in0Remark);
        _getRequest1_in0.setRequestKey(Integer.valueOf(726130291));
        _getRequest1_in0.setRequestid(Integer.valueOf(-494233552));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Requestlevel = null;
        _getRequest1_in0.setRequestlevel(_getRequest1_in0Requestlevel);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Requestname = null;
        _getRequest1_in0.setRequestname(_getRequest1_in0Requestname);
        javax.xml.bind.JAXBElement<weaver.conn.RecordSetTrans> _getRequest1_in0RsTrans = null;
        _getRequest1_in0.setRsTrans(_getRequest1_in0RsTrans);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Signdocids = null;
        _getRequest1_in0.setSigndocids(_getRequest1_in0Signdocids);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Signworkflowids = null;
        _getRequest1_in0.setSignworkflowids(_getRequest1_in0Signworkflowids);
        _getRequest1_in0.setSpeechAttachment(Integer.valueOf(-951922547));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Src = null;
        _getRequest1_in0.setSrc(_getRequest1_in0Src);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Status = null;
        _getRequest1_in0.setStatus(_getRequest1_in0Status);
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0SubmitNodeId = null;
        _getRequest1_in0.setSubmitNodeId(_getRequest1_in0SubmitNodeId);
        _getRequest1_in0.setTotalGroups(Integer.valueOf(1928597773));
        javax.xml.bind.JAXBElement<weaver.hrm.User> _getRequest1_in0User = null;
        _getRequest1_in0.setUser(_getRequest1_in0User);
        _getRequest1_in0.setUserId(Integer.valueOf(1170763376));
        _getRequest1_in0.setUserType(Integer.valueOf(-130535800));
        _getRequest1_in0.setWorkflowid(Integer.valueOf(-1994667692));
        javax.xml.bind.JAXBElement<java.lang.String> _getRequest1_in0Workflowtype = null;
        _getRequest1_in0.setWorkflowtype(_getRequest1_in0Workflowtype);
        weaver.soa.workflow.request.RequestInfo _getRequest1__return = port.getRequest1(_getRequest1_in0);
        System.out.println("getRequest1.result=" + _getRequest1__return);


        }
        {
        System.out.println("Invoking getProcessedRequestBySearch...");
        int _getProcessedRequestBySearch_in0 = 1815690076;
        java.lang.String _getProcessedRequestBySearch_in1 = "_getProcessedRequestBySearch_in1-1769005239";
        java.lang.String _getProcessedRequestBySearch_in2 = "_getProcessedRequestBySearch_in2-509585569";
        java.lang.String _getProcessedRequestBySearch_in3 = "_getProcessedRequestBySearch_in3174582706";
        weaver.soa.workflow.request.ArrayOfRequestBase _getProcessedRequestBySearch__return = port.getProcessedRequestBySearch(_getProcessedRequestBySearch_in0, _getProcessedRequestBySearch_in1, _getProcessedRequestBySearch_in2, _getProcessedRequestBySearch_in3);
        System.out.println("getProcessedRequestBySearch.result=" + _getProcessedRequestBySearch__return);


        }
        {
        System.out.println("Invoking nextNodeBySubmit...");
        weaver.soa.workflow.request.RequestInfo _nextNodeBySubmit_in0 = new weaver.soa.workflow.request.RequestInfo();
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit_in0Creatorid = null;
        _nextNodeBySubmit_in0.setCreatorid(_nextNodeBySubmit_in0Creatorid);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit_in0Description = null;
        _nextNodeBySubmit_in0.setDescription(_nextNodeBySubmit_in0Description);
        javax.xml.bind.JAXBElement<weaver.soa.workflow.request.DetailTableInfo> _nextNodeBySubmit_in0DetailTableInfo = null;
        _nextNodeBySubmit_in0.setDetailTableInfo(_nextNodeBySubmit_in0DetailTableInfo);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit_in0Hostid = null;
        _nextNodeBySubmit_in0.setHostid(_nextNodeBySubmit_in0Hostid);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit_in0IsNextFlow = null;
        _nextNodeBySubmit_in0.setIsNextFlow(_nextNodeBySubmit_in0IsNextFlow);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit_in0Lastoperator = null;
        _nextNodeBySubmit_in0.setLastoperator(_nextNodeBySubmit_in0Lastoperator);
        javax.xml.bind.JAXBElement<weaver.soa.workflow.request.MainTableInfo> _nextNodeBySubmit_in0MainTableInfo = null;
        _nextNodeBySubmit_in0.setMainTableInfo(_nextNodeBySubmit_in0MainTableInfo);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit_in0Remindtype = null;
        _nextNodeBySubmit_in0.setRemindtype(_nextNodeBySubmit_in0Remindtype);
        javax.xml.bind.JAXBElement<weaver.soa.workflow.request.RequestLog> _nextNodeBySubmit_in0RequestLog = null;
        _nextNodeBySubmit_in0.setRequestLog(_nextNodeBySubmit_in0RequestLog);
        javax.xml.bind.JAXBElement<weaver.workflow.request.RequestManager> _nextNodeBySubmit_in0RequestManager = null;
        _nextNodeBySubmit_in0.setRequestManager(_nextNodeBySubmit_in0RequestManager);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit_in0Requestid = null;
        _nextNodeBySubmit_in0.setRequestid(_nextNodeBySubmit_in0Requestid);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit_in0Requestlevel = null;
        _nextNodeBySubmit_in0.setRequestlevel(_nextNodeBySubmit_in0Requestlevel);
        javax.xml.bind.JAXBElement<weaver.conn.RecordSetTrans> _nextNodeBySubmit_in0RsTrans = null;
        _nextNodeBySubmit_in0.setRsTrans(_nextNodeBySubmit_in0RsTrans);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit_in0Workflowid = null;
        _nextNodeBySubmit_in0.setWorkflowid(_nextNodeBySubmit_in0Workflowid);
        int _nextNodeBySubmit_in1 = -986536035;
        int _nextNodeBySubmit_in2 = 1969924068;
        java.lang.String _nextNodeBySubmit_in3 = "_nextNodeBySubmit_in31221523215";
        boolean _nextNodeBySubmit__return = port.nextNodeBySubmit(_nextNodeBySubmit_in0, _nextNodeBySubmit_in1, _nextNodeBySubmit_in2, _nextNodeBySubmit_in3);
        System.out.println("nextNodeBySubmit.result=" + _nextNodeBySubmit__return);


        }
        {
        System.out.println("Invoking getMyRequestBySearch...");
        int _getMyRequestBySearch_in0 = -1167147017;
        java.lang.String _getMyRequestBySearch_in1 = "_getMyRequestBySearch_in1-1161298680";
        java.lang.String _getMyRequestBySearch_in2 = "_getMyRequestBySearch_in2230326353";
        java.lang.String _getMyRequestBySearch_in3 = "_getMyRequestBySearch_in3848779667";
        weaver.soa.workflow.request.ArrayOfRequestBase _getMyRequestBySearch__return = port.getMyRequestBySearch(_getMyRequestBySearch_in0, _getMyRequestBySearch_in1, _getMyRequestBySearch_in2, _getMyRequestBySearch_in3);
        System.out.println("getMyRequestBySearch.result=" + _getMyRequestBySearch__return);


        }
        {
        System.out.println("Invoking getRequest2...");
        int _getRequest2_in0 = 846895732;
        int _getRequest2_in1 = 904840524;
        weaver.soa.workflow.request.RequestInfo _getRequest2__return = port.getRequest2(_getRequest2_in0, _getRequest2_in1);
        System.out.println("getRequest2.result=" + _getRequest2__return);


        }
        {
        System.out.println("Invoking getPropValue...");
        java.lang.String _getPropValue_in0 = "_getPropValue_in0-137108469";
        java.lang.String _getPropValue_in1 = "_getPropValue_in1491733377";
        java.lang.String _getPropValue__return = port.getPropValue(_getPropValue_in0, _getPropValue_in1);
        System.out.println("getPropValue.result=" + _getPropValue__return);


        }
        {
        System.out.println("Invoking writeLog1...");
        java.lang.String _writeLog1_in0 = "_writeLog1_in0-1143131810";
        java.lang.Object _writeLog1_in1 = null;
        port.writeLog1(_writeLog1_in0, _writeLog1_in1);


        }
        {
        System.out.println("Invoking getRightMenu...");
        int _getRightMenu_in0 = -528935265;
        int _getRightMenu_in1 = -465685378;
        int _getRightMenu_in2 = 1941402166;
        int _getRightMenu_in3 = -1458754313;
        int _getRightMenu_in4 = -1084470506;
        boolean _getRightMenu_in5 = true;
        java.lang.String _getRightMenu__return = port.getRightMenu(_getRightMenu_in0, _getRightMenu_in1, _getRightMenu_in2, _getRightMenu_in3, _getRightMenu_in4, _getRightMenu_in5);
        System.out.println("getRightMenu.result=" + _getRightMenu__return);


        }
        {
        System.out.println("Invoking forwardFlow...");
        int _forwardFlow_in0 = 1722165586;
        int _forwardFlow_in1 = -1152772625;
        java.lang.String _forwardFlow_in2 = "_forwardFlow_in21037785398";
        java.lang.String _forwardFlow_in3 = "_forwardFlow_in3661794756";
        java.lang.String _forwardFlow_in4 = "_forwardFlow_in41885027174";
        boolean _forwardFlow__return = port.forwardFlow(_forwardFlow_in0, _forwardFlow_in1, _forwardFlow_in2, _forwardFlow_in3, _forwardFlow_in4);
        System.out.println("forwardFlow.result=" + _forwardFlow__return);


        }
        {
        System.out.println("Invoking getPendingRequestBySearch...");
        int _getPendingRequestBySearch_in0 = 757483014;
        java.lang.String _getPendingRequestBySearch_in1 = "_getPendingRequestBySearch_in1-1482317366";
        java.lang.String _getPendingRequestBySearch_in2 = "_getPendingRequestBySearch_in21580016964";
        java.lang.String _getPendingRequestBySearch_in3 = "_getPendingRequestBySearch_in3-559101972";
        weaver.soa.workflow.request.ArrayOfRequestBase _getPendingRequestBySearch__return = port.getPendingRequestBySearch(_getPendingRequestBySearch_in0, _getPendingRequestBySearch_in1, _getPendingRequestBySearch_in2, _getPendingRequestBySearch_in3);
        System.out.println("getPendingRequestBySearch.result=" + _getPendingRequestBySearch__return);


        }
        {
        System.out.println("Invoking nextNodeBySubmit1...");
        weaver.soa.workflow.request.RequestInfo _nextNodeBySubmit1_in0 = new weaver.soa.workflow.request.RequestInfo();
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit1_in0Creatorid = null;
        _nextNodeBySubmit1_in0.setCreatorid(_nextNodeBySubmit1_in0Creatorid);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit1_in0Description = null;
        _nextNodeBySubmit1_in0.setDescription(_nextNodeBySubmit1_in0Description);
        javax.xml.bind.JAXBElement<weaver.soa.workflow.request.DetailTableInfo> _nextNodeBySubmit1_in0DetailTableInfo = null;
        _nextNodeBySubmit1_in0.setDetailTableInfo(_nextNodeBySubmit1_in0DetailTableInfo);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit1_in0Hostid = null;
        _nextNodeBySubmit1_in0.setHostid(_nextNodeBySubmit1_in0Hostid);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit1_in0IsNextFlow = null;
        _nextNodeBySubmit1_in0.setIsNextFlow(_nextNodeBySubmit1_in0IsNextFlow);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit1_in0Lastoperator = null;
        _nextNodeBySubmit1_in0.setLastoperator(_nextNodeBySubmit1_in0Lastoperator);
        javax.xml.bind.JAXBElement<weaver.soa.workflow.request.MainTableInfo> _nextNodeBySubmit1_in0MainTableInfo = null;
        _nextNodeBySubmit1_in0.setMainTableInfo(_nextNodeBySubmit1_in0MainTableInfo);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit1_in0Remindtype = null;
        _nextNodeBySubmit1_in0.setRemindtype(_nextNodeBySubmit1_in0Remindtype);
        javax.xml.bind.JAXBElement<weaver.soa.workflow.request.RequestLog> _nextNodeBySubmit1_in0RequestLog = null;
        _nextNodeBySubmit1_in0.setRequestLog(_nextNodeBySubmit1_in0RequestLog);
        javax.xml.bind.JAXBElement<weaver.workflow.request.RequestManager> _nextNodeBySubmit1_in0RequestManager = null;
        _nextNodeBySubmit1_in0.setRequestManager(_nextNodeBySubmit1_in0RequestManager);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit1_in0Requestid = null;
        _nextNodeBySubmit1_in0.setRequestid(_nextNodeBySubmit1_in0Requestid);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit1_in0Requestlevel = null;
        _nextNodeBySubmit1_in0.setRequestlevel(_nextNodeBySubmit1_in0Requestlevel);
        javax.xml.bind.JAXBElement<weaver.conn.RecordSetTrans> _nextNodeBySubmit1_in0RsTrans = null;
        _nextNodeBySubmit1_in0.setRsTrans(_nextNodeBySubmit1_in0RsTrans);
        javax.xml.bind.JAXBElement<java.lang.String> _nextNodeBySubmit1_in0Workflowid = null;
        _nextNodeBySubmit1_in0.setWorkflowid(_nextNodeBySubmit1_in0Workflowid);
        int _nextNodeBySubmit1_in1 = 774684406;
        int _nextNodeBySubmit1_in2 = -1615575306;
        java.lang.String _nextNodeBySubmit1_in3 = "_nextNodeBySubmit1_in3-1317026915";
        java.lang.String _nextNodeBySubmit1_in4 = "_nextNodeBySubmit1_in4-256460681";
        boolean _nextNodeBySubmit1__return = port.nextNodeBySubmit1(_nextNodeBySubmit1_in0, _nextNodeBySubmit1_in1, _nextNodeBySubmit1_in2, _nextNodeBySubmit1_in3, _nextNodeBySubmit1_in4);
        System.out.println("nextNodeBySubmit1.result=" + _nextNodeBySubmit1__return);


        }
        {
        System.out.println("Invoking whetherMustInputRemark...");
        int _whetherMustInputRemark_in0 = -1898771568;
        int _whetherMustInputRemark_in1 = 1807573132;
        int _whetherMustInputRemark_in2 = -1993756568;
        int _whetherMustInputRemark_in3 = -123306197;
        int _whetherMustInputRemark_in4 = 1548062501;
        boolean _whetherMustInputRemark__return = port.whetherMustInputRemark(_whetherMustInputRemark_in0, _whetherMustInputRemark_in1, _whetherMustInputRemark_in2, _whetherMustInputRemark_in3, _whetherMustInputRemark_in4);
        System.out.println("whetherMustInputRemark.result=" + _whetherMustInputRemark__return);


        }
        {
        System.out.println("Invoking deleteRequest...");
        int _deleteRequest_in0 = -1045061219;
        boolean _deleteRequest__return = port.deleteRequest(_deleteRequest_in0);
        System.out.println("deleteRequest.result=" + _deleteRequest__return);


        }
        {
        System.out.println("Invoking loadTemplateProp...");
        java.lang.String _loadTemplateProp_in0 = "_loadTemplateProp_in01287015301";
        com.itg.soabus.oaservice.AnyType2AnyTypeMap _loadTemplateProp__return = port.loadTemplateProp(_loadTemplateProp_in0);
        System.out.println("loadTemplateProp.result=" + _loadTemplateProp__return);


        }

        System.exit(0);
    }

}
